# Generated by Django 5.2.4 on 2025-08-04 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('styles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='style',
            name='pillow',
            field=models.ImageField(blank=True, default='nameOfPhoto.png', upload_to=''),
        ),
    ]
