# Generated by Django 5.2.4 on 2025-08-05 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('styles', '0005_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
