# Generated by Django 5.2.4 on 2025-08-07 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('styles', '0007_profile_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='chats',
            field=models.ManyToManyField(blank=True, related_name='participants', to='styles.chat'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='content',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='chat',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_set', to='styles.profile'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='receiver',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='chat',
            name='sender',
            field=models.CharField(max_length=100),
        ),
    ]
