# Generated by Django 5.2.4 on 2025-08-08 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('styles', '0008_profile_chats_alter_chat_content_alter_chat_profile_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='content',
            new_name='speakingPartnerUsername',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='date',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='chats',
        ),
        migrations.AlterField(
            model_name='chat',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='styles.profile'),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=100)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='styles.chat')),
            ],
        ),
    ]
