# Generated by Django 5.2.4 on 2025-08-08 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('styles', '0009_rename_content_chat_speakingpartnerusername_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='receiver',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
